#!/usr/bin/env python

import subprocess, sys, os

foodmeDir = os.path.dirname(os.path.dirname(os.path.dirname(os.path.realpath(__file__))))
toolsDir = os.path.join(foodmeDir, 'tools')


def main():
	sys.exit(subprocess.call([os.path.join(toolsDir, 'update.py')], shell=True))

if __name__ == '__main__':
	main()