#!/usr/bin/env python

import os, sys, time, subprocess

"""
Checks your git commit with JSHint. Only checks staged files
"""
def jshint():
    
    errors = []
    
    # get all staged files
    f = os.popen('git diff --cached --name-only --diff-filter=ACM')
    
    for file in f.read().splitlines():

        # makes sure we're dealing javascript files
        if file.endswith('.js') and not file.startswith('node_modules/'):    	

            g = os.popen('jshint ' + file)
        
            # add all errors from all files together
            for error in g.readlines():
                errors.append(error)
    
    # got errors?
    if errors:
        for i, error in enumerate(errors):
            print error,
		
        # Abort the commit
        return False
    
    # All good
    return True


def serverStart():
    return True
    errors = []
    subprocess.call(["npm", "start"], cwd=".\\server\\", shell=True)

    # g = subprocess.call(['npm', 'start'], cwd='.\\server')
    # time.sleep(2)
    # returnVal = g.close()
    # print(returnVal)
    
if __name__ == '__main__':
    if jshint():
        if serverStart():
            sys.exit(0)
    sys.exit(1)

