#!/bin/bash
sudo iptables -t nat --flush
sudo iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 80 -j REDIRECT --to-port 3000
sudo forever start -l forever.log -a -o out.log -e err.log --spinSleepTime 10000 --minUptime 1000 /root/foodme/server/bin/www
